In [30]:
import numpy as np

In [31]:
myarr = np.array([[3,6,37,7]],np.int64)

In [32]:
myarr[0,1]


np.int64(6)

In [33]:
myarray = np.array([3,6,37,7],np.int64)

In [34]:
myarray[2]

np.int64(37)

In [35]:
myarr.shape

(1, 4)

In [36]:
myarr.dtype

dtype('int64')

In [37]:
myarr

array([[ 3,  6, 37,  7]])

In [38]:
myarr

array([[ 3,  6, 37,  7]])

   # Array creation : conversion from other python structure 

In [39]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [40]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
listarray.dtype

dtype('int64')

In [42]:
listarray.shape


(3, 3)

In [43]:
listarray.size

9

In [44]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [45]:
zeros

NameError: name 'zeros' is not defined

In [46]:
rng = np.arange(15)


In [47]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
lspace = np.linspace(1,5,4)

In [49]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [50]:
emp = np.empty((4,6))

emp

In [ ]:
emp_like=np.empty_like(lspace)

In [ ]:
emp_like

In [ ]:
ide = np.identity(45)

In [ ]:
ide

In [ ]:
ide.shape

In [ ]:
arr = np.arange(99)

In [ ]:
arr

In [ ]:
arr.reshape(3,33)

In [ ]:
arr.ravel()

In [ ]:
arr.shape

In [ ]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
ar=np.array(x)

In [ ]:
ar

In [ ]:
ar.sum(axis=0)

In [ ]:
ar.sum(axis=1)

In [ ]:
ar.T

In [ ]:
ar.flat

In [ ]:
for item in ar.flat:
    print(item)

In [ ]:
ar.ndim

In [ ]:
ar.size

In [ ]:
ar.nbytes

In [ ]:
one = np.array([1,3,4,634,2])

In [ ]:
one.argmax()

In [ ]:
one.argmin()

In [ ]:
one.argsort()

In [ ]:
ar

In [ ]:
ar.argmin()

In [ ]:
ar.argmax()

In [ ]:
ar.argmax(axis=0)

In [ ]:
ar.argmax(axis=1)

In [ ]:
ar.argsort(axis=0)

In [ ]:
ar2= np.array([[1,2,1],[4,0,6],[8,1,0]])


In [ ]:
ar+ar2

In [ ]:
ar*ar2

In [ ]:
ar-ar2

In [ ]:
np.sqrt(ar)


In [ ]:
np.where(ar>5)

In [ ]:
np.count_nonzero(ar)

In [ ]:
np.nonzero(ar)

In [ ]:
import sys 

In [ ]:
py_ar = [0,4,55,2]

In [ ]:
py_ar = np.array(py_ar)

In [ ]:
sys.getsizeof(py_ar)